writer:
  _target_: logger.WandbWriter
  project_name: EFDL_DDPM_HW1
  run_name: train_full_#4_change_optimizer
  mode: online
dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  num_workers: 4
  pin_memory: true
model:
  _target_: modeling.diffusion.DiffusionModel
  betas:
  - 0.0001
  - 0.02
  num_timesteps: 1000
unet:
  _target_: modeling.unet.UnetModel
  in_channels: 3
  out_channels: 3
  hidden_size: 64
optimizer:
  _target_: torch.optim.Adam
  lr: 1.0e-05
trainer:
  device: cuda
  n_epochs: 5
augmentation:
  random_flip: true
